[package]
name = "test_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
tokio = {version = "1.39.1", features = ["full"] }
warp = { version = "0.3.7"}
serde ={ version = "1.0", features = ["derive"] }